### ISSUE TITLE
Instructor mode double active courses tabs

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#76] opened 2023-03-29 18:40 UTC
![image](https://user-images.githubusercontent.com/129228337/228636204-76d18ced-d67c-4b34-aef5-85f787a0dd5a.png)

**Comment by josh-havens** [comment] 2023-03-29 19:18
Duplicate of #45

**Closed by josh-havens** 2023-03-29 19:18 UTC
Labels: reported bug, duplicate
