### ISSUE TITLE
After switching from Student to Administrator the Add Course button disappears and won't return until refresh or relogging in

### ISSUE THREAD

**Issue by SAStevens1** [GlobalUniversity/ArkTrainingNetwork#74] opened 2023-03-29 17:01 UTC
![image](https://user-images.githubusercontent.com/129208341/228613358-2020d2a1-e5e6-4a8a-955a-930d7f3d8618.png)

**Comment by josh-havens** [comment] 2023-03-29 19:20
Duplicate of #68 . Fixed in dev

**Closed by josh-havens** 2023-03-29 19:20 UTC
Labels: fixed in dev, verified issue, administrator, student
