### ISSUE TITLE
Program Requirement Buttons

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#55] opened 2023-03-28 21:13 UTC
Why are these buttons so sneaky? I haven't seen very many examples in our system of buttons being in the heading banner.
![Program Requirements](https://user-images.githubusercontent.com/129097082/228368184-92378df1-dcca-4b57-988e-d3a6185b0883.png)

**Comment by kdegarmo** [comment] 2023-03-28 21:48
Duplicate of item #39

**Closed by kdegarmo** 2023-03-28 21:48 UTC
Labels: duplicate, enhancement, ui issue
